-- ===== RLS POLICIES =====

-- PATIENTS TABLE
ALTER TABLE patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on patients" 
  ON patients FOR SELECT 
  USING (true);

CREATE POLICY "Allow public insert on patients" 
  ON patients FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Allow public update on patients" 
  ON patients FOR UPDATE 
  USING (true);

CREATE POLICY "Allow public delete on patients" 
  ON patients FOR DELETE 
  USING (true);

-- SERVICE CATALOG TABLE
ALTER TABLE service_catalog DISABLE ROW LEVEL SECURITY;

-- NURSES TABLE
ALTER TABLE nurses DISABLE ROW LEVEL SECURITY;

-- LAB TECHNICIANS TABLE
ALTER TABLE lab_technicians DISABLE ROW LEVEL SECURITY;

-- PHYSIOTHERAPISTS TABLE
ALTER TABLE physiotherapists DISABLE ROW LEVEL SECURITY;

-- SERVICE ORDERS TABLE
ALTER TABLE service_orders DISABLE ROW LEVEL SECURITY;

-- PAYMENT TRANSACTIONS TABLE
ALTER TABLE payment_transactions DISABLE ROW LEVEL SECURITY;

-- NOTIFICATIONS TABLE
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- FAVORITES TABLE
ALTER TABLE favorites DISABLE ROW LEVEL SECURITY;

-- REVIEWS TABLE
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;

-- PATIENT ADDRESSES TABLE
ALTER TABLE patient_addresses DISABLE ROW LEVEL SECURITY;

-- PATIENT SETTINGS TABLE
ALTER TABLE patient_settings DISABLE ROW LEVEL SECURITY;

-- PROVIDER DOCUMENTS TABLE
ALTER TABLE provider_documents DISABLE ROW LEVEL SECURITY;

-- PROVIDER SERVICES TABLE
ALTER TABLE provider_services DISABLE ROW LEVEL SECURITY;

-- ORDER SERVICES TABLE
ALTER TABLE order_services DISABLE ROW LEVEL SECURITY;

-- ORDER ADDRESSES TABLE
ALTER TABLE order_addresses DISABLE ROW LEVEL SECURITY;

-- ORDER NOTES TABLE
ALTER TABLE order_notes DISABLE ROW LEVEL SECURITY;

-- ORDER PAYMENTS TABLE
ALTER TABLE order_payments DISABLE ROW LEVEL SECURITY;

-- GRANT PERMISSIONS TO ANON ROLE
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon;

-- DEFAULT PRIVILEGES FOR FUTURE TABLES
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO anon;
